"""
Risk Scoring API
=================
A small, general-purpose "upload your data, get a validated risk model"
service. Point it at any tabular dataset with a binary outcome column
(churn, default, fraud, no-show -- anything) and it trains a logistic
regression classifier, validates it on a held-out split, and hands back
an API you can score new records against.

Built as a reusable tool for client engagements, not a one-off demo:
the /train endpoint works on any CSV, not just the churn dataset this
was originally built alongside.

Run locally:
    uvicorn app.main:app --reload

Interactive docs (auto-generated by FastAPI) are then at /docs.
"""
import io
import time

import pandas as pd
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List, Dict, Any

from app import ml

app = FastAPI(
    title="Risk Scoring API",
    description="Upload tabular data, get a validated binary-outcome risk model, "
                 "then score new records against it. Built by Tamearon Mullings.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # demo-scope: a real client deployment would restrict this
    allow_methods=["*"],
    allow_headers=["*"],
)

from fastapi.responses import JSONResponse
from fastapi.requests import Request

@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=500,
        content={"error": "internal_error", "detail": "Something went wrong processing this request. "
                                                        "If this persists, check that your data matches the expected format."},
    )

START_TIME = time.time()


class PredictRequest(BaseModel):
    records: List[Dict[str, Any]]


@app.get("/health")
def health():
    return {"status": "ok", "uptime_seconds": round(time.time() - START_TIME, 1)}


@app.post("/train")
async def train(
    file: UploadFile = File(..., description="CSV file with your data"),
    target_column: str = Form(..., description="Name of the binary outcome column to predict"),
    feature_columns: Optional[str] = Form(
        None, description="Optional comma-separated list of columns to use as features. "
                           "If omitted, numeric and low-cardinality categorical columns are auto-selected."
    ),
    model_name: Optional[str] = Form(None, description="Optional friendly name for this model"),
):
    if not file.filename.endswith(".csv"):
        raise HTTPException(400, "Only .csv files are supported.")
    try:
        raw = await file.read()
        df = pd.read_csv(io.BytesIO(raw))
    except Exception as e:
        raise HTTPException(400, f"Could not read CSV: {e}")

    feat_list = [c.strip() for c in feature_columns.split(",")] if feature_columns else None

    try:
        metadata = ml.train_model(df, target_column, feat_list, model_name)
    except ml.TrainingError as e:
        raise HTTPException(422, str(e))

    return metadata


@app.get("/models")
def models():
    return ml.list_models()


@app.get("/models/{model_id}")
def model_detail(model_id: str):
    meta = ml.get_model_metadata(model_id)
    if meta is None:
        raise HTTPException(404, f"No model with id '{model_id}'.")
    return meta


@app.delete("/models/{model_id}")
def remove_model(model_id: str):
    existed = ml.delete_model(model_id)
    if not existed:
        raise HTTPException(404, f"No model with id '{model_id}'.")
    return {"deleted": model_id}


@app.post("/predict/{model_id}")
def predict(model_id: str, req: PredictRequest):
    if not req.records:
        raise HTTPException(400, "records list is empty.")
    results = ml.predict(model_id, req.records)
    if results is None:
        raise HTTPException(404, f"No model with id '{model_id}'.")
    return {"model_id": model_id, "predictions": results}


@app.get("/")
def root():
    return {
        "service": "Risk Scoring API",
        "docs": "/docs",
        "endpoints": ["/health", "/train", "/models", "/models/{model_id}", "/predict/{model_id}"],
    }
